# Generated by Django 4.2.30 on 2026-08-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('ALL', 'All'), ('ORDER', 'Order & Gate Pass'), ('OFFER', 'Special Offers'), ('LOYALTY', 'Loyalty Points'), ('CART', 'Smart Cart'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=20)),
                ('icon_type', models.CharField(default='SYSTEM', max_length=50)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
