# Generated by Django 4.2.30 on 2026-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='operating_hours',
            field=models.CharField(default='সকাল ১০ - রাত ৯টা', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
    ]
