# Generated by Django 4.2.30 on 2026-08-14 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Stock Received (+Stock)'), ('DAMAGE', 'Damaged/Expired (-Stock)'), ('TRANSFER_OUT', 'Transferred to other branch (-Stock)'), ('SALE', 'Customer Checkout (-Stock)')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
            ],
        ),
    ]
