# Generated by Django 4.2.30 on 2026-08-14 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_image_branch_name_bn_branch_operating_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_discount_amount_product_image_and_more'),
        ('orders', '0003_order_discount_amount_order_loyalty_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('customer', 'product', 'branch')},
            },
        ),
    ]
